apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot
  template:
    metadata:
      labels:
        app: springboot
    spec:
      containers:
      - name: springboot
        image: mymbbcontainerregistry.azurecr.io/sachinpandit1729/mbb4k85s:latest
        ports:
        - containerPort: 12005
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: springboot-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: springboot-config
              key: DB_PORT
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: springboot-config
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: springboot-config
              key: DB_USER
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: DB_PASS
      imagePullSecrets:
      - name: acr-secret