spring.application.name=mbblab3

server.port=12001

spring.datasource.url=jdbc:mysql://azure-sachin-mysql-server.mysql.database.azure.com:3306/mbblab1
spring.datasource.username=sachin
spring.datasource.password=Aug@@2025

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQLDialect

